---
# This role installs opendj. It will listen on the default ports (389/636 for ssl)
# Assumes 'java' is installed and on the path
# TODO: Import sample ldif, schema
#

- include: install.yml
- include: config.yml
